#!/usr/bin/python3
str = "Python is an interpreted, interactive, object-oriented programming\
 language that combines remarkable power with very clear syntax"
str = str.split("object-oriented programming language")[1].split("with Python")[0]
print(str)
